name: Train ML Model

on:
    workflow_dispatch:
    push:

env:
    EXPORT_NAME: 'training-exports.zip'
    EXPORT_LOCATION: 'exports/en-tw-transformer-nmt'
    ASSET_DIR: 'data/en-tw'
    PROJECT_DIR: 'projects/en-tw-transformer-nmt'
    TRAIN_SAMPLE: 5000

jobs:
    train:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    cache: 'pip'
                    python-version: '3.11.7'

            -   name: Install dependencies
                run: |
                    mkdir -p $export_dir
                    python -m pip install --upgrade pip
                    pip install jupyter keras papermill
                    pip install -r requirements.txt
                env:
                    export_dir: ${{ env.EXPORT_LOCATION }}

            -   name: Check for latest release
                id: check_release
                run: |
                    echo "Checking for the latest release..."
                    latest_release=$(gh api repos/${{ github.repository }}/releases/latest --silent || echo "no_release")
                    if [[ "$latest_release" == "no_release" ]]; then
                      echo "No release found. Proceeding without downloading."
                      echo "::set-output name=release_exists::false"
                    else
                      echo "Release found. Preparing to download assets."
                      echo "::set-output name=release_exists::true"
                    fi
                env:
                    GITHUB_TOKEN: ${{ github.token }}

            -   name: Download latest release assets
                if: steps.check_release.outputs.release_exists == 'true'
                run: |
                    gh release download --repo ${{ github.repository }} \
                        --dir ${{ env.EXPORT_LOCATION }} \
                        -p '*.best.keras' -p '*.lang.idx'
                env:
                    GITHUB_TOKEN: ${{ github.token }}

            -   name: Execute Pre-processor Notebook
                run: |
                    papermill ${{ env.PROJECT_DIR }}/tokenizer.ipynb tokenizer.ipynb --prepare-only \
                        -p asset_dir "${{ env.ASSET_DIR }}"
                    jupyter nbconvert tokenizer.ipynb --to script
                    python tokenizer.py

            -   name: Execute Training Notebook
                run: |
                    papermill ${{ env.PROJECT_DIR }}/main.ipynb out.ipynb --prepare-only \
                        -p exports_dir "${{ env.EXPORT_LOCATION }}" \
                        -p asset_dir "${{ env.ASSET_DIR }}"
                        -p training_sample ${{ env.TRAIN_SAMPLE }} \
                        -p num_attention_layers 4
                    jupyter nbconvert out.ipynb --to script
                    python out.py

            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ github.token }}
                with:
                    tag_name: ${{ github.run_id }}
                    release_name: Release for run ${{ github.run_id }}
                    draft: false
                    prerelease: false

            -   name: Upload Release Assets
                id: upload-release-assets
                uses: dwenegar/upload-release-assets@v1
                env:
                    GITHUB_TOKEN: ${{ github.token }}
                with:
                    release_id: ${{ steps.create_release.outputs.id }}
                    assets_path: ${{ env.EXPORT_LOCATION }}
                

